# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you: 
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: web 开发笔记
description: "记录web开发中遇到的各种问题，及解决问题的思路和过程。如果你有好的建议或想法，欢迎前来交流。"
keywords: "web开发笔记,web开发,前端开发,html5,nodejs"
author:
  name: "zooble"
  email: "wenliang.web@gmail.com"

baseurl: "" # the subpath of your site, e.g. /blog
url: "https://xwenliang.cn" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: ""
github_username: xwenliang

# Build settings
theme: minima
minima:
  date_format: "%Y-%m-%d %H:%M:%S"

plugins:
  - jekyll-feed
  - jekyll-paginate

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

exclude:
  - repro/

timezone: Asia/Shanghai

paginate: 10
paginate_path: "/page:num/"
# 文章摘要
# By default this is the first paragraph of content in the post, 
# however it can be customized by setting a excerpt_separator variable in front matter or _config.yml.
# excerpt_separator: <!--more-->
show_excerpts: true
